### PR TITLE
Bugfix/574 oom on many revisions

### LINKED ISSUE #574: Viewing entity with many revisions runs out of memory
When an entity with 227 revisions is clicked, an empty page is shown and the following is logged:

```
Apr 15 10:09:19 prd42 Apache-SR: [Wed Apr 15 10:09:20 2015] [error] [client 195.169.126.161] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 74 bytes) in /opt/openconext/OpenConext-serviceregistry-5.1.2/simplesamlphp-1.13.2/lib/SimpleSAML/XHTML/Template.php on line 569, referer: https://serviceregistry.surfconext.nl/simplesaml/module.php/janus/dashboard.php/entities
```

### PR DESCRIPTION
**Pull request by relaxnow**
Implement simple pagination controls.

peak_memory_usage is now no more than 30Mb.
Fixed #574 .

### CODE REVIEW

File: templates/editentity/history.php [hunk 1]
```diff
@@ -63,4 +72,16 @@
                 <?php endif; ?>
             </div>
         <?php endforeach; ?>
+    <?php  ?>
+    <div id="history_pagination_controls" style="width: 50%">
+        <br style="clear: both">
+        <?php if (isset($this->data['history_prev_offset'])): ?>
+        <a style="display: inline-block; float: left"
+           href="editentity.php?eid=<?= htmlspecialchars($entity->getEid()); ?>&selectedtab=8&history_offset=<?= $this->data['history_prev_offset'] ?>#history">&leftarrow; Later revisions</a>
```
Comment (thijskh) [inline templates/editentity/history.php]: `htmlspecialchars` should be `urlencode`, `&` should be `&amp;` I guess...
Same below.

**Comment by thijskh** [comment]
Except for comment: :+1:

File: templates/editentity/history.php (hunk 1 above)
Comment (relaxnow) [inline templates/editentity/history.php]: Well, actually in theory it should be 'htmlspecialchars(urlencode())' as it's a URL encoded in HTML. In practice this is always an integer so it doesn't really matter. 
But as a part of a [Defense of depth](http://en.wikipedia.org/wiki/Defense_in_depth_%28computing%29) approach I really should've done it anyway, good catch, thanks!
