### PR TITLE
Also check if a key is explicitly marked for signing before rejecting it

### LINKED ISSUE #570: Certificate import fails on given metadata
When trying to import metadata from the URL below (either via URL or copy-pasting into XML textfield) the metadata certificate does not get imported, while the other metadata fields do get imported. Manually adding the cert after the entity is created does work.
Why does importing the cert fail?

https://crebain2.ics.muni.cz/Shibboleth.sso/Metadata

### PR DESCRIPTION
**Pull request by thijskh**
If a key is marked both encryption AND signing, the test would reject it because it considered it to be an encryption key.

Fixes #570

### CODE REVIEW

File: lib/Importer.php [hunk 1]
```diff
@@ -211,7 +211,8 @@ private function _addCertificateMetaData(&$parsedMetaData)
 
         foreach ($certKeys as $certKey) {
             if (isset($parsedMetaData[$certKey . 'X509Certificate']) &&
-                (!isset($parsedMetaData[$certKey . 'encryption']) ||
+                ( (isset($parsedMetaData[$certKey . 'signing']) && $parsedMetaData[$certKey . 'signing']) ||
+                    !isset($parsedMetaData[$certKey . 'encryption']) ||
```
Comment (relaxnow) [inline lib/Importer.php]: Could you refactor this to something like this:

```php
if (!isset($parsedMetaData[$certKey . 'X509Certificate'])) {
  continue;
}
// Skip encryption keys if we don't support encryption usage.
if ($encryptionEnabled && !$parsedMetaData[$certKey . 'signing']) {
  continue;
}
```

Comment (thijskh) [inline lib/Importer.php]: I can indeed factor out the first condition like that, see extra commit. However, the other three are or'ed so not easily split out into individual "continued" checks.

Comment (relaxnow) [inline lib/Importer.php]: Actually I think it is that simple, because those if conditions are simply guarding that we don't use encryption keys (not encryption and signing keys) if we are not using encryption.

Comment (relaxnow) [inline lib/Importer.php]: Though this bit could *really* use tests.

**Comment by relaxnow** [comment]
@thijskh do you agree with my conclusion that we could reduce it to:

```php
if (!isset($parsedMetaData[$certKey . 'X509Certificate'])) {
  continue;
}
// Skip encryption keys if we don't support encryption usage.
if ($encryptionEnabled && !$parsedMetaData[$certKey . 'signing']) {
  continue;
}
```
?
